# Generated by Django 4.2.6 on 2023-10-27 23:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ciudad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Ciudad')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Provincia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Provincia')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Propiedad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Disponibles')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('description', models.TextField(verbose_name='Descripción de la propiedad')),
                ('estado', models.PositiveSmallIntegerField(choices=[(1, 'Libre'), (2, 'Alquilada'), (3, 'En refacción'), (4, 'Fuera de servicio')])),
                ('operacion', models.PositiveSmallIntegerField(choices=[(1, 'Alquiler'), (2, 'Alquiler temporal'), (3, 'Venta'), (4, 'Permuta')])),
                ('image', models.ImageField(blank=True, null=True, upload_to='alquiler', verbose_name='Portada')),
                ('costo', models.FloatField(verbose_name='Costo')),
                ('ciudad', models.ManyToManyField(to='app.ciudad', verbose_name='Ciudad')),
            ],
            options={
                'verbose_name': 'Disponible',
                'verbose_name_plural': 'Disponibles',
            },
        ),
        migrations.AddField(
            model_name='ciudad',
            name='provincia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.provincia', verbose_name='Provincia'),
        ),
    ]
