# Generated by Django 4.2.6 on 2023-11-01 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_remove_propiedad_image_propiedadimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='propiedad',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='alquilerimg', verbose_name='Portada'),
        ),
        migrations.DeleteModel(
            name='PropiedadImage',
        ),
    ]
