# Generated by Django 4.2.6 on 2023-10-29 00:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_ciudad_provincia_delete_provincia'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Estado')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Estado',
                'verbose_name_plural': 'Estados',
            },
        ),
        migrations.AlterField(
            model_name='operacion',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Operación'),
        ),
        migrations.AlterField(
            model_name='propiedad',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Propiedades'),
        ),
        migrations.AlterField(
            model_name='propiedad',
            name='estado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.estado', verbose_name='Estado'),
        ),
    ]
