# Generated by Django 4.2.6 on 2023-10-28 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_operacion_alter_propiedad_operacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propiedad',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='alquilerimg', verbose_name='Portada'),
        ),
    ]
