# Generated by Django 4.2.6 on 2023-10-29 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_propiedad_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ciudad',
            options={'verbose_name': 'Ciudad', 'verbose_name_plural': 'Ciudades'},
        ),
        migrations.AlterModelOptions(
            name='operacion',
            options={'verbose_name': 'Tipo de operación', 'verbose_name_plural': 'Tipos de operación'},
        ),
        migrations.AlterModelOptions(
            name='propiedad',
            options={'verbose_name': 'Propiedad disponible', 'verbose_name_plural': 'Propiedades disponibles'},
        ),
        migrations.AlterModelOptions(
            name='provincia',
            options={'verbose_name': 'Provincia', 'verbose_name_plural': 'Provincias'},
        ),
    ]
