# Generated by Django 4.2.6 on 2023-10-29 00:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_ciudad_options_alter_operacion_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ciudad',
            name='provincia',
        ),
        migrations.DeleteModel(
            name='Provincia',
        ),
    ]
