# Generated by Django 4.2.6 on 2023-10-29 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_estado_alter_operacion_name_alter_propiedad_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ciudad',
            name='codigo_postal',
            field=models.IntegerField(blank=True, null=True, verbose_name='CodigoPostal'),
        ),
        migrations.AlterField(
            model_name='propiedad',
            name='costo',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Costo'),
        ),
    ]
