# Generated by Django 4.2.6 on 2023-11-03 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_foto_remove_propiedad_image_propiedad_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propiedad',
            name='image',
        ),
        migrations.DeleteModel(
            name='Foto',
        ),
        migrations.AddField(
            model_name='propiedad',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='alquilerimg', verbose_name='Portada'),
        ),
    ]
